server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/identity/ {
        proxy_pass http://zorbit-identity:3099/;
    }

    location /api/authorization/ {
        proxy_pass http://zorbit-authorization:3098/;
    }

    location /api/navigation/ {
        proxy_pass http://zorbit-navigation:3097/;
    }

    location /api/messaging/ {
        proxy_pass http://zorbit-messaging:3096/;
    }

    location /api/pii-vault/ {
        proxy_pass http://zorbit-pii-vault:3095/;
    }

    location /api/audit/ {
        proxy_pass http://zorbit-audit:3094/;
    }

    location /api/customer/ {
        proxy_pass http://sample-customer-service:3093/;
    }

    location /api/admin-console/ {
        proxy_pass http://zorbit-admin-console-server:3020/;
    }

    location /api/app/pcg4/ {
        proxy_pass http://127.0.0.1:3111/api/app/pcg4/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
