import { DemoSegmentType, StepAction, DemoStep } from '../models/entities/demo-segment.entity';

interface BuiltinSegmentSeed {
  id: string;
  title: string;
  description: string;
  duration: string;
  type: DemoSegmentType;
  builtin: true;
  category: string;
  steps: DemoStep[];
  videoUrl: string | null;
  ttsEnabled: boolean;
}

export const builtinSegments: BuiltinSegmentSeed[] = [
  {
    id: 'DEM-0001',
    title: 'Login & Dashboard Overview',
    description: 'Walk through the login process and explore the main dashboard with summary cards and quick actions.',
    duration: '2:30',
    type: DemoSegmentType.INTERACTIVE,
    builtin: true,
    category: 'onboarding',
    steps: [
      { seq: 1, action: StepAction.INFO, target: '', value: 'Welcome to Zorbit! Let\'s start by logging in.', delay_ms: 2000, narration: 'Welcome to Zorbit. Let us start by logging in.' },
      { seq: 2, action: StepAction.NAVIGATE, target: '/login', value: '', delay_ms: 1000, narration: 'Navigate to the login page.' },
      { seq: 3, action: StepAction.HIGHLIGHT, target: 'input[name="email"]', value: '', delay_ms: 1500, narration: 'Enter your email address here.' },
      { seq: 4, action: StepAction.TYPE, target: 'input[name="email"]', value: 'demo@zorbit.io', delay_ms: 500, narration: '' },
      { seq: 5, action: StepAction.HIGHLIGHT, target: 'input[name="password"]', value: '', delay_ms: 1000, narration: 'Enter your password.' },
      { seq: 6, action: StepAction.TYPE, target: 'input[name="password"]', value: 'demo123', delay_ms: 500, narration: '' },
      { seq: 7, action: StepAction.CLICK, target: 'button[type="submit"]', value: '', delay_ms: 2000, narration: 'Click Sign In to access your dashboard.' },
      { seq: 8, action: StepAction.NAVIGATE, target: '/dashboard', value: '', delay_ms: 1500, narration: 'This is the main dashboard.' },
      { seq: 9, action: StepAction.HIGHLIGHT, target: '.summary-cards', value: '', delay_ms: 2000, narration: 'Summary cards show key metrics at a glance.' },
      { seq: 10, action: StepAction.INFO, target: '', value: 'The dashboard is fully configurable. You can add, remove, and rearrange widgets.', delay_ms: 3000, narration: 'The dashboard is fully configurable.' },
    ],
    videoUrl: null,
    ttsEnabled: true,
  },
  {
    id: 'DEM-0002',
    title: 'User Management',
    description: 'Learn how to create, edit, and manage users within your organization.',
    duration: '3:00',
    type: DemoSegmentType.INTERACTIVE,
    builtin: true,
    category: 'admin',
    steps: [
      { seq: 1, action: StepAction.NAVIGATE, target: '/users', value: '', delay_ms: 1000, narration: 'Navigate to the Users page.' },
      { seq: 2, action: StepAction.INFO, target: '', value: 'The Users page shows all users in your organization.', delay_ms: 2000, narration: 'The Users page shows all users in your organization.' },
      { seq: 3, action: StepAction.HIGHLIGHT, target: '[data-testid="create-user-btn"]', value: '', delay_ms: 1500, narration: 'Click here to create a new user.' },
      { seq: 4, action: StepAction.HIGHLIGHT, target: '.data-table', value: '', delay_ms: 2000, narration: 'The table shows user details including name, email token, and status.' },
      { seq: 5, action: StepAction.INFO, target: '', value: 'Note: Email addresses are stored as PII tokens. Raw emails are never displayed in the admin console.', delay_ms: 3000, narration: 'Email addresses are stored as PII tokens for security.' },
      { seq: 6, action: StepAction.HIGHLIGHT, target: '.user-status-badge', value: '', delay_ms: 1500, narration: 'Status badges show whether users are active or inactive.' },
      { seq: 7, action: StepAction.INFO, target: '', value: 'Users inherit permissions from their assigned roles.', delay_ms: 2000, narration: 'Users inherit permissions from their assigned roles.' },
    ],
    videoUrl: null,
    ttsEnabled: true,
  },
  {
    id: 'DEM-0003',
    title: 'Organization Management',
    description: 'Understand the organization hierarchy and how to manage org settings.',
    duration: '2:45',
    type: DemoSegmentType.INTERACTIVE,
    builtin: true,
    category: 'admin',
    steps: [
      { seq: 1, action: StepAction.NAVIGATE, target: '/organizations', value: '', delay_ms: 1000, narration: 'Navigate to Organizations.' },
      { seq: 2, action: StepAction.INFO, target: '', value: 'Organizations are the top-level namespace in Zorbit. All resources are scoped to an organization.', delay_ms: 3000, narration: 'Organizations are the top-level namespace. All resources are scoped to an organization.' },
      { seq: 3, action: StepAction.HIGHLIGHT, target: '.org-table', value: '', delay_ms: 2000, narration: 'Each organization has a unique short hash ID like O-92AF.' },
      { seq: 4, action: StepAction.INFO, target: '', value: 'Organization IDs follow the Zorbit short hash pattern: PREFIX-XXXX.', delay_ms: 2000, narration: 'Organization IDs follow the short hash pattern.' },
      { seq: 5, action: StepAction.HIGHLIGHT, target: '[data-testid="org-details"]', value: '', delay_ms: 2000, narration: 'Click on an organization to see its details and child orgs.' },
      { seq: 6, action: StepAction.INFO, target: '', value: 'Namespace isolation ensures users can only access resources within their organization.', delay_ms: 2500, narration: 'Namespace isolation ensures proper access control.' },
    ],
    videoUrl: null,
    ttsEnabled: true,
  },
  {
    id: 'DEM-0004',
    title: 'Role & Privilege Assignment',
    description: 'Learn how to create roles, assign privileges, and manage access control.',
    duration: '3:30',
    type: DemoSegmentType.INTERACTIVE,
    builtin: true,
    category: 'admin',
    steps: [
      { seq: 1, action: StepAction.NAVIGATE, target: '/roles', value: '', delay_ms: 1000, narration: 'Navigate to the Roles page.' },
      { seq: 2, action: StepAction.INFO, target: '', value: 'Roles define what users can do in the system. Each role has a set of privileges.', delay_ms: 3000, narration: 'Roles define what users can do. Each role has a set of privileges.' },
      { seq: 3, action: StepAction.HIGHLIGHT, target: '[data-testid="create-role-btn"]', value: '', delay_ms: 1500, narration: 'Click here to create a new role.' },
      { seq: 4, action: StepAction.HIGHLIGHT, target: '.role-privileges-list', value: '', delay_ms: 2000, narration: 'Privileges use dot notation like identity.user.read or dashboard.designer.write.' },
      { seq: 5, action: StepAction.INFO, target: '', value: 'Privileges are organized into sections. Each section groups related capabilities.', delay_ms: 2500, narration: 'Privileges are organized into sections for easy management.' },
      { seq: 6, action: StepAction.INFO, target: '', value: 'The super_admin role has all privileges. Create custom roles for fine-grained access control.', delay_ms: 3000, narration: 'Create custom roles for fine-grained access control.' },
      { seq: 7, action: StepAction.HIGHLIGHT, target: '.role-assignment', value: '', delay_ms: 2000, narration: 'Assign roles to users from the role detail page.' },
    ],
    videoUrl: null,
    ttsEnabled: true,
  },
  {
    id: 'DEM-0005',
    title: 'Navigation Configuration',
    description: 'Configure the sidebar menu, manage sections, and control menu item visibility.',
    duration: '2:00',
    type: DemoSegmentType.INTERACTIVE,
    builtin: true,
    category: 'admin',
    steps: [
      { seq: 1, action: StepAction.NAVIGATE, target: '/navigation-admin', value: '', delay_ms: 1000, narration: 'Navigate to Navigation Admin.' },
      { seq: 2, action: StepAction.INFO, target: '', value: 'The navigation system is privilege-driven. Menu items are automatically shown based on user roles.', delay_ms: 3000, narration: 'The navigation system is privilege-driven.' },
      { seq: 3, action: StepAction.HIGHLIGHT, target: '.nav-sections', value: '', delay_ms: 2000, narration: 'Sections organize menu items into logical groups.' },
      { seq: 4, action: StepAction.HIGHLIGHT, target: '.nav-menu-item', value: '', delay_ms: 2000, narration: 'Each menu item is linked to a privilege and a frontend route.' },
      { seq: 5, action: StepAction.INFO, target: '', value: 'Routes use handlebars templates like /org/{{org_id}}/users that resolve at runtime.', delay_ms: 2500, narration: 'Routes use handlebars templates that resolve at runtime.' },
    ],
    videoUrl: null,
    ttsEnabled: true,
  },
  {
    id: 'DEM-0006',
    title: 'Audit Log Review',
    description: 'Learn how to search and filter audit logs to track platform activity.',
    duration: '2:15',
    type: DemoSegmentType.INTERACTIVE,
    builtin: true,
    category: 'reports',
    steps: [
      { seq: 1, action: StepAction.NAVIGATE, target: '/audit', value: '', delay_ms: 1000, narration: 'Navigate to the Audit page.' },
      { seq: 2, action: StepAction.INFO, target: '', value: 'Every action in the platform is recorded as an audit event with a Kafka event envelope.', delay_ms: 3000, narration: 'Every action is recorded as an audit event.' },
      { seq: 3, action: StepAction.HIGHLIGHT, target: '.audit-filters', value: '', delay_ms: 2000, narration: 'Use filters to search by event type, user, time range, or namespace.' },
      { seq: 4, action: StepAction.HIGHLIGHT, target: '.audit-table', value: '', delay_ms: 2000, narration: 'The audit log shows event type, timestamp, user, and payload details.' },
      { seq: 5, action: StepAction.INFO, target: '', value: 'Audit events follow the domain.entity.action naming convention.', delay_ms: 2000, narration: 'Events follow the domain dot entity dot action naming convention.' },
    ],
    videoUrl: null,
    ttsEnabled: true,
  },
  {
    id: 'DEM-0007',
    title: 'PII Vault Operations',
    description: 'Understand how sensitive data is tokenized and managed through the PII Vault.',
    duration: '2:45',
    type: DemoSegmentType.INTERACTIVE,
    builtin: true,
    category: 'reports',
    steps: [
      { seq: 1, action: StepAction.NAVIGATE, target: '/pii-vault', value: '', delay_ms: 1000, narration: 'Navigate to the PII Vault page.' },
      { seq: 2, action: StepAction.INFO, target: '', value: 'The PII Vault stores all personally identifiable information. Operational databases only store tokens.', delay_ms: 3000, narration: 'The PII Vault stores all personally identifiable information securely.' },
      { seq: 3, action: StepAction.HIGHLIGHT, target: '.pii-audit-log', value: '', delay_ms: 2000, narration: 'This page shows PII access audit logs, not raw PII data.' },
      { seq: 4, action: StepAction.INFO, target: '', value: 'PII tokens look like PII-92AF. They can only be resolved by authorized services.', delay_ms: 2500, narration: 'PII tokens can only be resolved by authorized services.' },
      { seq: 5, action: StepAction.INFO, target: '', value: 'The admin console never displays raw PII values — only tokens and access logs.', delay_ms: 2500, narration: 'The admin console never displays raw PII values.' },
      { seq: 6, action: StepAction.HIGHLIGHT, target: '.pii-access-details', value: '', delay_ms: 2000, narration: 'Each access event shows who accessed what data and when.' },
    ],
    videoUrl: null,
    ttsEnabled: true,
  },
  {
    id: 'DEM-0008',
    title: 'Messaging & Events',
    description: 'Explore Kafka topics, monitor event flow, and manage dead letter queues.',
    duration: '3:00',
    type: DemoSegmentType.INTERACTIVE,
    builtin: true,
    category: 'reports',
    steps: [
      { seq: 1, action: StepAction.NAVIGATE, target: '/messaging', value: '', delay_ms: 1000, narration: 'Navigate to the Messaging page.' },
      { seq: 2, action: StepAction.INFO, target: '', value: 'Zorbit uses Kafka for event-driven communication between services.', delay_ms: 2500, narration: 'Zorbit uses Kafka for event-driven communication.' },
      { seq: 3, action: StepAction.HIGHLIGHT, target: '.kafka-topics', value: '', delay_ms: 2000, narration: 'Topics are organized by domain. Each event type has its own topic.' },
      { seq: 4, action: StepAction.HIGHLIGHT, target: '.dlq-section', value: '', delay_ms: 2000, narration: 'The Dead Letter Queue shows events that failed processing.' },
      { seq: 5, action: StepAction.INFO, target: '', value: 'Events follow the canonical Zorbit envelope with eventId, timestamp, source, namespace, and payload.', delay_ms: 3000, narration: 'Events follow the canonical Zorbit envelope format.' },
      { seq: 6, action: StepAction.HIGHLIGHT, target: '.messaging-health', value: '', delay_ms: 2000, narration: 'The health indicator shows Kafka cluster status.' },
    ],
    videoUrl: null,
    ttsEnabled: true,
  },
  {
    id: 'DEM-0009',
    title: 'Dashboard Designer',
    description: 'Learn how to create, configure, and arrange dashboard widgets with role-based visibility.',
    duration: '3:15',
    type: DemoSegmentType.INTERACTIVE,
    builtin: true,
    category: 'admin',
    steps: [
      { seq: 1, action: StepAction.NAVIGATE, target: '/dashboard', value: '', delay_ms: 1000, narration: 'Navigate to the Dashboard.' },
      { seq: 2, action: StepAction.INFO, target: '', value: 'The dashboard supports 5 widget types: count, chart, table, list, and gauge.', delay_ms: 3000, narration: 'The dashboard supports five widget types.' },
      { seq: 3, action: StepAction.HIGHLIGHT, target: '[data-testid="designer-toggle"]', value: '', delay_ms: 1500, narration: 'Click the designer toggle to enter configuration mode.' },
      { seq: 4, action: StepAction.HIGHLIGHT, target: '.widget-grid', value: '', delay_ms: 2000, narration: 'In designer mode, you can drag and drop widgets to rearrange them.' },
      { seq: 5, action: StepAction.HIGHLIGHT, target: '[data-testid="add-widget-btn"]', value: '', delay_ms: 1500, narration: 'Click Add Widget to create a new widget.' },
      { seq: 6, action: StepAction.INFO, target: '', value: 'Each widget has a metric query — an API path template that fetches the data.', delay_ms: 2500, narration: 'Each widget has a metric query that fetches its data.' },
      { seq: 7, action: StepAction.INFO, target: '', value: 'Widgets can be restricted to specific roles. Users only see widgets matching their roles.', delay_ms: 3000, narration: 'Widgets can be restricted to specific roles for visibility control.' },
    ],
    videoUrl: null,
    ttsEnabled: true,
  },
  {
    id: 'DEM-0010',
    title: 'Quick Start Onboarding',
    description: 'A rapid overview of the complete Zorbit platform covering all key features in one session.',
    duration: '3:00',
    type: DemoSegmentType.INTERACTIVE,
    builtin: true,
    category: 'onboarding',
    steps: [
      { seq: 1, action: StepAction.INFO, target: '', value: 'Welcome to the Zorbit Quick Start! This guide covers the entire platform in 3 minutes.', delay_ms: 3000, narration: 'Welcome to the Zorbit Quick Start guide.' },
      { seq: 2, action: StepAction.NAVIGATE, target: '/dashboard', value: '', delay_ms: 1000, narration: 'The dashboard is your home base.' },
      { seq: 3, action: StepAction.INFO, target: '', value: 'Zorbit follows MACH architecture: Microservices, API-first, Cloud-native, Headless.', delay_ms: 3000, narration: 'Zorbit follows MACH architecture.' },
      { seq: 4, action: StepAction.NAVIGATE, target: '/users', value: '', delay_ms: 1000, narration: 'Users are managed under the Identity service.' },
      { seq: 5, action: StepAction.NAVIGATE, target: '/roles', value: '', delay_ms: 1000, narration: 'Roles and privileges control access.' },
      { seq: 6, action: StepAction.NAVIGATE, target: '/audit', value: '', delay_ms: 1000, narration: 'Every action is audited.' },
      { seq: 7, action: StepAction.NAVIGATE, target: '/messaging', value: '', delay_ms: 1000, narration: 'Services communicate through Kafka events.' },
      { seq: 8, action: StepAction.NAVIGATE, target: '/pii-vault', value: '', delay_ms: 1000, narration: 'Sensitive data is tokenized in the PII Vault.' },
      { seq: 9, action: StepAction.NAVIGATE, target: '/settings', value: '', delay_ms: 1000, narration: 'Configure your profile and API settings here.' },
      { seq: 10, action: StepAction.INFO, target: '', value: 'That\'s the complete platform! Explore each section in detail using the other demo segments.', delay_ms: 3000, narration: 'That is the complete platform. Explore each section in detail using other demo segments.' },
    ],
    videoUrl: null,
    ttsEnabled: true,
  },
];
