export const API_CONFIG = {
  IDENTITY_URL: import.meta.env.VITE_IDENTITY_URL || '/api/identity',
  AUTHORIZATION_URL: import.meta.env.VITE_AUTHORIZATION_URL || '/api/authorization',
  NAVIGATION_URL: import.meta.env.VITE_NAVIGATION_URL || '/api/navigation',
  MESSAGING_URL: import.meta.env.VITE_MESSAGING_URL || '/api/messaging',
  PII_VAULT_URL: import.meta.env.VITE_PII_VAULT_URL || '/api/pii-vault',
  AUDIT_URL: import.meta.env.VITE_AUDIT_URL || '/api/audit',
  CUSTOMER_URL: import.meta.env.VITE_CUSTOMER_URL || '/api/customer',
  ADMIN_CONSOLE_URL: import.meta.env.VITE_ADMIN_CONSOLE_URL || '/api/unified-console',
  PCG4_URL: import.meta.env.VITE_PCG4_URL || '/api/app/pcg4',
  CHAT_URL: import.meta.env.VITE_CHAT_URL || '/api/chat',
  RTC_URL: import.meta.env.VITE_RTC_URL || '/api/rtc',
  CHAT_WS_URL: import.meta.env.VITE_CHAT_WS_URL || '',
  RTC_WS_URL: import.meta.env.VITE_RTC_WS_URL || '',
  LIVEKIT_URL: import.meta.env.VITE_LIVEKIT_URL || 'wss://zorbit.scalatics.com:7881',
  UW_WORKFLOW_URL: import.meta.env.VITE_UW_WORKFLOW_URL || '/api/uw-workflow',
  HI_DECISIONING_URL: import.meta.env.VITE_HI_DECISIONING_URL || '/api/hi-decisioning',
  HI_QUOTATION_URL: import.meta.env.VITE_HI_QUOTATION_URL || '/api/hi-quotation',
  MI_QUOTATION_URL: import.meta.env.VITE_MI_QUOTATION_URL || '/api/mi-quotation',
  FORM_BUILDER_URL: import.meta.env.VITE_FORM_BUILDER_URL || '/api/form-builder',
  PRODUCT_PRICING_URL: import.meta.env.VITE_PRODUCT_PRICING_URL || '/api/product-pricing',
  NOTIFICATION_URL: import.meta.env.VITE_NOTIFICATION_URL || '/api/notification',
  VOICE_ENGINE_URL: import.meta.env.VITE_VOICE_ENGINE_URL || '/api/voice-engine',
  JAYNA_URL: import.meta.env.VITE_JAYNA_URL || '/api/jayna',
};
